"""empty message

Revision ID: 2347ec9c659e
Revises: d8fdbf2c8449
Create Date: 2020-05-03 16:05:52.732638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2347ec9c659e'
down_revision = 'd8fdbf2c8449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('algorithm_grade', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'circuits', 'users', ['student_id'], ['student_id'])
    op.drop_column('circuits', 'grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'circuits', type_='foreignkey')
    op.drop_column('circuits', 'algorithm_grade')
    # ### end Alembic commands ###
