"""empty message

Revision ID: 43f3fe0f1fa1
Revises: c031ff41e477
Create Date: 2020-04-17 16:14:40.702198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f3fe0f1fa1'
down_revision = 'c031ff41e477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'circuits', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'circuits', type_='unique')
    # ### end Alembic commands ###
