"""empty message

Revision ID: 5336af3a4239
Revises: f51dc5f88a62
Create Date: 2020-05-03 15:49:23.162111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5336af3a4239'
down_revision = 'f51dc5f88a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('circuit_input', sa.Text(length=4294000000), nullable=False))
    op.add_column('circuits', sa.Column('circuit_output_json', sa.Text(length=4294000000), nullable=False))
    op.add_column('circuits', sa.Column('grade', sa.Integer(), nullable=True))
    op.alter_column('circuits', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_unique_constraint(None, 'circuits', ['circuit_name'])
    op.drop_column('circuits', 'circuit_json')
    op.add_column('users', sa.Column('confirm_admin', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Integer(), nullable=True))
    op.drop_index('student_id', table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.create_index('student_id', 'users', ['student_id'], unique=True)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'confirm_admin')
    op.add_column('circuits', sa.Column('circuit_json', mysql.LONGTEXT(), nullable=False))
    op.drop_constraint(None, 'circuits', type_='unique')
    op.alter_column('circuits', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('circuits', 'grade')
    op.drop_column('circuits', 'circuit_output_json')
    op.drop_column('circuits', 'circuit_input')
    # ### end Alembic commands ###
