"""empty message

Revision ID: 667482a3ef3c
Revises: a1857e1de307
Create Date: 2020-04-07 19:34:34.637386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667482a3ef3c'
down_revision = 'a1857e1de307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###
