"""empty message

Revision ID: 85179f84d02d
Revises: 34fe96f53049
Create Date: 2020-04-17 16:17:32.933200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85179f84d02d'
down_revision = '34fe96f53049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circuits', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'circuits', 'users', ['student_id'], ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'circuits', type_='foreignkey')
    op.alter_column('circuits', 'student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
