"""empty message

Revision ID: 8a485e37ab39
Revises: 85179f84d02d
Create Date: 2020-04-17 16:19:34.851798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a485e37ab39'
down_revision = '85179f84d02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'circuits', ['circuit_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'circuits', type_='unique')
    # ### end Alembic commands ###
