"""empty message

Revision ID: 8b73c43ab13f
Revises: dbd984bc6cb2
Create Date: 2020-05-03 16:18:07.145655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b73c43ab13f'
down_revision = 'dbd984bc6cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'circuits', 'users', ['student_id'], ['student_id'])
    op.drop_column('circuits', 'grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'circuits', type_='foreignkey')
    # ### end Alembic commands ###
