"""empty message

Revision ID: a1857e1de307
Revises: e1482772398c
Create Date: 2020-04-04 15:44:32.547949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1857e1de307'
down_revision = 'e1482772398c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_date')
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###
