"""empty message

Revision ID: d8fdbf2c8449
Revises: f2ea7c8df456
Create Date: 2020-05-03 15:59:24.097380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fdbf2c8449'
down_revision = 'f2ea7c8df456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'circuits', 'users', ['student_id'], ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'circuits', type_='foreignkey')
    # ### end Alembic commands ###
