"""empty message

Revision ID: e2bc71487e9c
Revises: 8a485e37ab39
Create Date: 2020-04-17 18:03:17.467140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2bc71487e9c'
down_revision = '8a485e37ab39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('circuit_input', sa.Text(length=4294000000), nullable=False))
    op.add_column('circuits', sa.Column('circuit_output_json', sa.Text(length=4294000000), nullable=False))
    op.drop_column('circuits', 'circuit_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('circuit_json', mysql.LONGTEXT(), nullable=False))
    op.drop_column('circuits', 'circuit_output_json')
    op.drop_column('circuits', 'circuit_input')
    # ### end Alembic commands ###
