"""empty message

Revision ID: f2ea7c8df456
Revises: e3b2267d59e3
Create Date: 2020-05-03 15:54:42.167188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ea7c8df456'
down_revision = 'e3b2267d59e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'circuits', 'users', ['student_id'], ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'circuits', type_='foreignkey')
    # ### end Alembic commands ###
