"""empty message

Revision ID: fa99a81d5808
Revises: 667482a3ef3c
Create Date: 2020-04-17 15:49:46.558901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa99a81d5808'
down_revision = '667482a3ef3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('circuit_name', sa.String(length=191), nullable=False),
    sa.Column('circuit_json', sa.Text(length=4294000000), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('student_id', table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.create_index('student_id', 'users', ['student_id'], unique=True)
    op.drop_table('circuits')
    # ### end Alembic commands ###
